"""
Question checklist catalog — loaded from configdata/question_catalog.yaml,
generated by scripts/csv_to_question_catalog_yaml.py from
docs/dr-egeria/resource_questions.csv (the source of truth for both that
YAML and the Dr.Egeria markdown processed into Egeria itself — see
docs/dr-egeria/foundations.md).

Backs the Scouting "Questions" checklist tab: for a given resource, which
of the authored Scouting questions are answerable today (and by which
analysis_catalog.yaml analysis), which are gaps, and which need a human via
Enrichment — filterable by the same Perspective set used elsewhere in the
UI.

`purposes` carries the Purpose kinds a question serves (2026-08-24). Purpose
is the PRIMARY dispatch axis, Perspective the secondary one — measured over
the whole catalog, no Perspective reaches an analysis that another Perspective
doesn't also reach, so Perspective can rank but cannot select. Purpose orders
what runs by default; it never excludes.

`answering.checks` carries the finer `analysis_id:check_name` join added
2026-08-24, alongside `analysis_ids` rather than replacing it. Several
analyses bundle unrelated checks — `repo_conventions` alone answers 7 of the
16 analysis-answerable questions across its 5 checks — so an analysis-level
join loses most of the information the question corpus actually carries.
Valid check names are declared in configdata/check_registry.yaml; note that
`findings_kind` there is not always the analysis id. `checks` is empty for
questions answered by a whole analysis with no per-check decomposition, and
for every question whose CSV row has not been given check refs yet, so
consumers must treat empty as "fall back to analysis_ids", never as "no
checks apply". Mirrors analysis_catalog_reader.py's loading convention exactly
(frozen dataclass, lru_cache-backed loader, clear_cache() testing hook).

This module does NOT read Egeria live — the YAML (ultimately the CSV) is
the source of truth for now, matching how csv_to_dr_egeria_questions.py's
own output is also generated rather than read back from Egeria. A future
pass could query Egeria's real Question/Perspective/ScopedBy elements
directly (see docs/dr-egeria/foundations.md's header comment on the
Unification Thread) — deliberately not built yet.
"""
from __future__ import annotations

import functools
from dataclasses import dataclass, field
from pathlib import Path

import yaml

_DEFAULT_CONFIG_PATH = Path(__file__).parent.parent / "configdata" / "question_catalog.yaml"


@dataclass(frozen=True)
class QuestionAnswering:
    kind: str  # analysis | direct | registry | human | chart | gap | partial | mixed | unknown
    analysis_ids: list[str] = field(default_factory=list)
    checks: list[str] = field(default_factory=list)
    note: str = ""

    def to_dict(self) -> dict:
        return {"kind": self.kind, "analysis_ids": self.analysis_ids,
                "checks": self.checks, "note": self.note}


@dataclass(frozen=True)
class QuestionCatalogEntry:
    question: str
    stage: str
    perspectives: list[str]
    answering: QuestionAnswering
    purposes: list[str] = field(default_factory=list)
    #: Granularity the answer is a single value at (design §18.3): one or more
    #: of resource / container / member / field. Asked above its level a
    #: question answers as a ranked distribution. Default "resource" so entries
    #: generated before the column existed keep their meaning.
    levels: list[str] = field(default_factory=lambda: ["resource"])
    answering_mechanism: str = ""
    # What this question's answer can and cannot claim — the CSV's
    # Rationale/Source column. Carried to the UI because a caveat that lives
    # only in the catalog is a caveat nobody reading the answer ever sees.
    rationale: str = ""
    # What used to be wrong and when it changed — the catalog's changelog for
    # this row, past tense, for its maintainer. Kept apart from `rationale`
    # so a reader deciding how far to trust an answer is not handed the
    # build's history in the same breath.
    catalog_history: str = ""
    # True once the CSV's Status column reads "Retired" (2026-09-20,
    # SPEC-ADMIN-THE-FOUR-GAPS.md §4). The catalog is append-only — a
    # retired question is flagged, never removed or reworded, since a past
    # survey answer still refers to it exactly as it was asked. Consumers
    # must show retired questions distinctly, not hide them: hiding would
    # make an old answer's question untraceable from this browser.
    retired: bool = False

    def to_dict(self) -> dict:
        return {
            "question": self.question,
            "stage": self.stage,
            "perspectives": self.perspectives,
            "purposes": self.purposes,
            "levels": self.levels,
            "answering": self.answering.to_dict(),
            "answering_mechanism": self.answering_mechanism,
            "rationale": self.rationale,
            "catalog_history": self.catalog_history,
            "retired": self.retired,
        }


def _entry_from_yaml(raw: dict) -> QuestionCatalogEntry:
    answering_raw = raw.get("answering") or {}
    return QuestionCatalogEntry(
        question=raw["question"],
        stage=raw.get("stage", ""),
        perspectives=list(raw.get("perspectives") or []),
        purposes=list(raw.get("purposes") or []),
        levels=list(raw.get("levels") or ["resource"]),
        answering=QuestionAnswering(
            kind=answering_raw.get("kind", "unknown"),
            analysis_ids=list(answering_raw.get("analysis_ids") or []),
            checks=list(answering_raw.get("checks") or []),
            note=answering_raw.get("note", ""),
        ),
        answering_mechanism=raw.get("answering_mechanism", ""),
        rationale=raw.get("rationale", ""),
        catalog_history=raw.get("catalog_history", ""),
        retired=bool(raw.get("retired", False)),
    )


#: Reasons a returned question list is the length it is. `NOT_AUTHORED` is
#: the one this vocabulary exists for: before 2026-09-20 a resource type with
#: no authored questions and a resource type whose filters excluded everything
#: both returned `[]`, and a caller could not tell "nobody has written
#: questions for databases yet" from "there are database questions, none of
#: them are Scouting/Privacy ones" (design §1.1 item 3).
AUTHORED = "authored"                       #: entries were authored AND survived the filters
NOT_AUTHORED = "not_authored"               #: the catalog has no section for this resource type at all
AUTHORED_BUT_EMPTY = "authored_but_empty"   #: a section exists and is empty — a catalog in progress
FILTERED_TO_NOTHING = "filtered_to_nothing" #: questions exist; this phase/perspective combination has none

_ABSENCE_NOTES = {
    AUTHORED: "",
    NOT_AUTHORED: (
        "No questions have been authored for this resource type yet — this is "
        "a gap in the catalog, not a measured absence."
    ),
    AUTHORED_BUT_EMPTY: (
        "This resource type has a question catalog section, but it is empty — "
        "authoring has started and no question has landed yet."
    ),
    FILTERED_TO_NOTHING: (
        "Questions are authored for this resource type; none of them match "
        "this stage and Perspective combination."
    ),
}


class QuestionList(list):
    """The list of question dicts `get_questions()` has always returned, which
    now also knows *why* it is the length it is.

    A `list` subclass rather than a wrapper object on purpose. Every existing
    caller — the API routes, `context_compile`, `survey_definition_reader`,
    the stage pages — iterates, slices, `len()`s and JSON-serialises this
    value, and a real list keeps all of that working untouched. The honesty
    the design asks for rides along as attributes, so a caller that wants to
    distinguish "not authored" from "filtered to nothing" can, and one that
    does not is not broken to make the point.

    `absence` is `AUTHORED` whenever there is at least one entry; the three
    other values are the distinct ways of being empty.
    """

    resource_type: str = ""
    absence: str = AUTHORED
    #: True when the catalog has a section for this resource type at all,
    #: regardless of whether anything survived the filters.
    authored: bool = False

    @property
    def absence_reason(self) -> str:
        """Prose for the empty case, or "" when there are entries. Safe to
        render directly: it never claims a measurement that did not happen."""
        return _ABSENCE_NOTES.get(self.absence, "")

    def as_envelope(self) -> dict:
        """The list plus its state, for an API or UI caller that must render
        the difference rather than an empty table."""
        return {
            "resource_type": self.resource_type,
            "questions": list(self),
            "count": len(self),
            "authored": self.authored,
            "absence": self.absence,
            "absence_reason": self.absence_reason,
        }


#: The YAML key suffix each resource type's questions live under —
#: `repo_questions`, `database_questions`, and so on. The generator
#: (scripts/csv_to_question_catalog_yaml.py) emits one key per resource type
#: named in the CSV's `Resource Types` column; this reader discovers them
#: rather than naming them, so a newly authored type needs no change here.
_QUESTIONS_KEY_SUFFIX = "_questions"


@functools.lru_cache(maxsize=1)
def _load(config_path: Path = _DEFAULT_CONFIG_PATH) -> dict[str, list[QuestionCatalogEntry]]:
    """Every `<resource_type>_questions` section in the catalog, keyed by type.

    A resource type is present here IF AND ONLY IF the YAML has a section for
    it. That is the whole point: a missing key means "not authored", which
    `get_questions()` reports as such instead of as an empty list. Returning a
    fabricated `{"repo": []}` for every type would put the bug back.

    A missing config file yields `{}` — no type is authored, because there is
    no catalog. It used to yield `{"repo": []}`, which claimed repo questions
    had been authored and had come to nothing.
    """
    if not config_path.exists():
        return {}
    with open(config_path) as f:
        raw = yaml.safe_load(f) or {}

    return {
        key[: -len(_QUESTIONS_KEY_SUFFIX)]: [_entry_from_yaml(e) for e in (value or [])]
        for key, value in raw.items()
        if key.endswith(_QUESTIONS_KEY_SUFFIX) and key != _QUESTIONS_KEY_SUFFIX
    }


def authored_resource_types() -> list[str]:
    """Resource types the catalog has a section for, in catalog order."""
    return list(_load())


def is_authored(resource_type: str) -> bool:
    """Whether ANY question has been authored for this resource type.

    The cheap form of the distinction, for a caller that only needs to decide
    whether to offer a Questions tab at all.
    """
    return resource_type in _load()


def clear_cache() -> None:
    """Testing hook — the loader result is cached via lru_cache."""
    _load.cache_clear()


def get_questions(
    resource_type: str = "repo",
    phase: str | None = None,
    perspectives: list[str] | None = None,
    purposes: list[str] | None = None,
) -> QuestionList:
    """Return question catalog entries for a resource type, optionally
    filtered by funnel-stage phase and/or Perspective set, and optionally
    ORDERED by Purpose.

    phase: matched against the entry's (single) `stage` field
    (case-insensitive). A stage may be slash-combined (e.g.
    "Analysis/Enrichment", signaling an Analysis-first/Enrichment-fallback
    pattern — see docs/confidence-gated-validation-plan.md) — matches if
    `phase` equals ANY of the slash-separated parts, not just the whole
    string, so a question tagged "Analysis/Enrichment" shows up under both
    Analysis's and Enrichment's checklist.

    perspectives: OR-matched against each entry's perspectives list, same
    semantics as analysis_catalog_reader.get_analyses()'s perspective
    filter and the UI's activePerspectives multi-select — empty/None means
    no filter (show everything for the phase).

    purposes: **ORDERS, never excludes.** Entries serving any of the given
    Purposes sort first; everything else follows in catalog order. This is
    the asymmetry measured in docs/investigation-framing-design.md §3 —
    Purpose discriminates (overlap 0.22) and Perspective does not (0.37,
    strictly nested sets), so Perspective filters what is *shown* while
    Purpose ranks what comes *first*. Filtering on Purpose here would be a
    bug: nothing is hidden by it. Empty/None leaves catalog order untouched.

    Every returned entry carries a `derivation` key recording why it is in
    the result — which Perspectives and Purposes matched, and whether
    Purpose promoted it. That chain (Purpose + Perspective → question →
    analysis_ids) is the explanation a user actually asks for, and it is
    already implicit in this function; `derivation` just stops discarding
    it. See docs/context-compilation-design.md §11.

    **The return value is a `QuestionList`, not a bare list** (2026-09-20,
    design §1.1 item 3 / §13 Phase 0 item 1). It behaves as the list it
    always was, and carries `.authored` / `.absence` / `.absence_reason` so
    an empty result can say which kind of empty it is. `get_questions("database")`
    on a catalog with no database section is `NOT_AUTHORED` — a gap in the
    catalog — where `get_questions("repo", perspectives=["Privacy"])` finding
    nothing is `FILTERED_TO_NOTHING`. Those are the same length and opposite
    answers, and before this they were the same value.
    """
    catalog = _load()
    authored = resource_type in catalog
    entries = [e.to_dict() for e in catalog.get(resource_type, [])]
    authored_count = len(entries)

    if phase:
        phase_lower = phase.lower()
        entries = [
            e for e in entries
            if phase_lower in {part.strip().lower() for part in e["stage"].split("/")}
        ]

    if perspectives:
        wanted = {p.lower() for p in perspectives}
        entries = [
            e for e in entries
            if wanted.intersection(p.lower() for p in e["perspectives"])
        ]

    wanted_persp = {p.lower() for p in (perspectives or [])}
    wanted_purp = {p.lower() for p in (purposes or [])}

    for e in entries:
        matched_persp = [p for p in e["perspectives"] if p.lower() in wanted_persp]
        matched_purp = [p for p in e["purposes"] if p.lower() in wanted_purp]
        e["derivation"] = {
            "phase": phase or "",
            "matched_perspectives": matched_persp,
            "matched_purposes": matched_purp,
            "purpose_ranked": bool(matched_purp),
            "analysis_ids": list(e["answering"]["analysis_ids"]),
            "checks": list(e["answering"]["checks"]),
        }

    if wanted_purp:
        # Stable: promoted entries keep catalog order among themselves, and
        # so does everything else. Nothing is dropped.
        entries.sort(key=lambda e: not e["derivation"]["purpose_ranked"])

    result = QuestionList(entries)
    result.resource_type = resource_type
    result.authored = authored
    if entries:
        result.absence = AUTHORED
    elif not authored:
        result.absence = NOT_AUTHORED
    elif authored_count == 0:
        result.absence = AUTHORED_BUT_EMPTY
    else:
        result.absence = FILTERED_TO_NOTHING
    return result
